name: draggable_resizable_marker_map
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.10.0
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.6.1
  geolocator: ^13.0.2
  auto_route: ^9.3.0+1
  cached_network_image: ^3.4.1
  http: ^1.2.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.1
  widget_to_marker: ^1.0.6
  badges: ^3.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  collection: ^1.19.0
  flutter_box_transform: ^0.4.6
  animated_toggle_switch: ^0.8.4
  arrow_path: ^3.1.0
  flutter_gen: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  auto_route_generator: ^9.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
